/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EmployeeLoginRouteImport } from './routes/employee-login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedInquiriesRouteImport } from './routes/_authenticated/inquiries'
import { Route as AuthenticatedOutstandingRouteImport } from './routes/_authenticated/outstanding'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices/$id'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedQuotationsIndexRouteImport } from './routes/_authenticated/quotations/index'
import { Route as AuthenticatedQuotationsIdRouteImport } from './routes/_authenticated/quotations/$id'
import { Route as AuthenticatedQuotationsNewRouteImport } from './routes/_authenticated/quotations/new'
import { Route as AuthenticatedReceiptsIndexRouteImport } from './routes/_authenticated/receipts/index'
import { Route as AuthenticatedReceiptsIdRouteImport } from './routes/_authenticated/receipts/$id'
import { Route as AuthenticatedReceiptsNewRouteImport } from './routes/_authenticated/receipts/new'
import { Route as AuthenticatedInvoicesIdEditRouteImport } from './routes/_authenticated/invoices/$id_.edit'
import { Route as AuthenticatedQuotationsIdEditRouteImport } from './routes/_authenticated/quotations/$id_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLoginRoute = EmployeeLoginRouteImport.update({
  id: '/employee-login',
  path: '/employee-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInquiriesRoute = AuthenticatedInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutstandingRoute =
  AuthenticatedOutstandingRouteImport.update({
    id: '/outstanding',
    path: '/outstanding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsIndexRoute =
  AuthenticatedQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsIdRoute =
  AuthenticatedQuotationsIdRouteImport.update({
    id: '/quotations/$id',
    path: '/quotations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsNewRoute =
  AuthenticatedQuotationsNewRouteImport.update({
    id: '/quotations/new',
    path: '/quotations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptsIndexRoute =
  AuthenticatedReceiptsIndexRouteImport.update({
    id: '/receipts/',
    path: '/receipts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceiptsIdRoute = AuthenticatedReceiptsIdRouteImport.update({
  id: '/receipts/$id',
  path: '/receipts/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceiptsNewRoute =
  AuthenticatedReceiptsNewRouteImport.update({
    id: '/receipts/new',
    path: '/receipts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdEditRoute =
  AuthenticatedInvoicesIdEditRouteImport.update({
    id: '/invoices/$id_/edit',
    path: '/invoices/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsIdEditRoute =
  AuthenticatedQuotationsIdEditRouteImport.update({
    id: '/quotations/$id_/edit',
    path: '/quotations/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/employee-login': typeof EmployeeLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/outstanding': typeof AuthenticatedOutstandingRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/receipts/new': typeof AuthenticatedReceiptsNewRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/receipts/': typeof AuthenticatedReceiptsIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/quotations/$id/edit': typeof AuthenticatedQuotationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/employee-login': typeof EmployeeLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/outstanding': typeof AuthenticatedOutstandingRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/receipts/new': typeof AuthenticatedReceiptsNewRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/quotations': typeof AuthenticatedQuotationsIndexRoute
  '/receipts': typeof AuthenticatedReceiptsIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/quotations/$id/edit': typeof AuthenticatedQuotationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/employee-login': typeof EmployeeLoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/inquiries': typeof AuthenticatedInquiriesRoute
  '/_authenticated/outstanding': typeof AuthenticatedOutstandingRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/_authenticated/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/_authenticated/receipts/$id': typeof AuthenticatedReceiptsIdRoute
  '/_authenticated/receipts/new': typeof AuthenticatedReceiptsNewRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/_authenticated/receipts/': typeof AuthenticatedReceiptsIndexRoute
  '/_authenticated/invoices/$id_/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/_authenticated/quotations/$id_/edit': typeof AuthenticatedQuotationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/employee-login'
    | '/reset-password'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/inquiries'
    | '/outstanding'
    | '/payroll'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/quotations/$id'
    | '/quotations/new'
    | '/receipts/$id'
    | '/receipts/new'
    | '/invoices/'
    | '/quotations/'
    | '/receipts/'
    | '/invoices/$id/edit'
    | '/quotations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/employee-login'
    | '/reset-password'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/inquiries'
    | '/outstanding'
    | '/payroll'
    | '/settings'
    | '/invoices/$id'
    | '/invoices/new'
    | '/quotations/$id'
    | '/quotations/new'
    | '/receipts/$id'
    | '/receipts/new'
    | '/invoices'
    | '/quotations'
    | '/receipts'
    | '/invoices/$id/edit'
    | '/quotations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/auth'
    | '/employee-login'
    | '/reset-password'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/expenses'
    | '/_authenticated/inquiries'
    | '/_authenticated/outstanding'
    | '/_authenticated/payroll'
    | '/_authenticated/settings'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/quotations/$id'
    | '/_authenticated/quotations/new'
    | '/_authenticated/receipts/$id'
    | '/_authenticated/receipts/new'
    | '/_authenticated/invoices/'
    | '/_authenticated/quotations/'
    | '/_authenticated/receipts/'
    | '/_authenticated/invoices/$id_/edit'
    | '/_authenticated/quotations/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  EmployeeLoginRoute: typeof EmployeeLoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-login': {
      id: '/employee-login'
      path: '/employee-login'
      fullPath: '/employee-login'
      preLoaderRoute: typeof EmployeeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries': {
      id: '/_authenticated/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AuthenticatedInquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outstanding': {
      id: '/_authenticated/outstanding'
      path: '/outstanding'
      fullPath: '/outstanding'
      preLoaderRoute: typeof AuthenticatedOutstandingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/': {
      id: '/_authenticated/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AuthenticatedQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$id': {
      id: '/_authenticated/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AuthenticatedQuotationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/new': {
      id: '/_authenticated/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AuthenticatedQuotationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts/': {
      id: '/_authenticated/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof AuthenticatedReceiptsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts/$id': {
      id: '/_authenticated/receipts/$id'
      path: '/receipts/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof AuthenticatedReceiptsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receipts/new': {
      id: '/_authenticated/receipts/new'
      path: '/receipts/new'
      fullPath: '/receipts/new'
      preLoaderRoute: typeof AuthenticatedReceiptsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id_/edit': {
      id: '/_authenticated/invoices/$id_/edit'
      path: '/invoices/$id/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof AuthenticatedInvoicesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$id_/edit': {
      id: '/_authenticated/quotations/$id_/edit'
      path: '/quotations/$id/edit'
      fullPath: '/quotations/$id/edit'
      preLoaderRoute: typeof AuthenticatedQuotationsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedInquiriesRoute: typeof AuthenticatedInquiriesRoute
  AuthenticatedOutstandingRoute: typeof AuthenticatedOutstandingRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedQuotationsIdRoute: typeof AuthenticatedQuotationsIdRoute
  AuthenticatedQuotationsNewRoute: typeof AuthenticatedQuotationsNewRoute
  AuthenticatedReceiptsIdRoute: typeof AuthenticatedReceiptsIdRoute
  AuthenticatedReceiptsNewRoute: typeof AuthenticatedReceiptsNewRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedQuotationsIndexRoute: typeof AuthenticatedQuotationsIndexRoute
  AuthenticatedReceiptsIndexRoute: typeof AuthenticatedReceiptsIndexRoute
  AuthenticatedInvoicesIdEditRoute: typeof AuthenticatedInvoicesIdEditRoute
  AuthenticatedQuotationsIdEditRoute: typeof AuthenticatedQuotationsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedInquiriesRoute: AuthenticatedInquiriesRoute,
  AuthenticatedOutstandingRoute: AuthenticatedOutstandingRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedQuotationsIdRoute: AuthenticatedQuotationsIdRoute,
  AuthenticatedQuotationsNewRoute: AuthenticatedQuotationsNewRoute,
  AuthenticatedReceiptsIdRoute: AuthenticatedReceiptsIdRoute,
  AuthenticatedReceiptsNewRoute: AuthenticatedReceiptsNewRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedQuotationsIndexRoute: AuthenticatedQuotationsIndexRoute,
  AuthenticatedReceiptsIndexRoute: AuthenticatedReceiptsIndexRoute,
  AuthenticatedInvoicesIdEditRoute: AuthenticatedInvoicesIdEditRoute,
  AuthenticatedQuotationsIdEditRoute: AuthenticatedQuotationsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  EmployeeLoginRoute: EmployeeLoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
